import { Metadata } from "next";
import BookingDetail from "./components/BookingDetail";

export const metadata: Metadata = {
  title: "Booking Flight | SkyFly",
  description: "Generated by create next app",
};

export default function bookingPage() {
  return <BookingDetail />;
}
