import { Toaster } from "react-hot-toast";
import FormOtp from "./form";
import ToastListener from "@/components/ui/ToastListener";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Authentication | SkyFly",
  description: "Generated by create next app",
};

export default function OtpPage() {
  return (
    <>
      <Toaster position="top-right" reverseOrder={false} />
      <ToastListener />
      <FormOtp />
    </>
  );
}
