import { Metadata } from "next";
import NotificationPage from "./components/Notification";

export const metadata: Metadata = {
  title: "Notifications | SkyFly",
  description: "Generated by create next app",
};

export default function NotificationPages() {
  return <NotificationPage />;
}
