import { Metadata } from "next";
import HistoryPage from "./components/History";

export const metadata: Metadata = {
  title: "Booking History | SkyFly",
  description: "Generated by create next app",
};

export default function HistoryPages() {
  return <HistoryPage />;
}