import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "../../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="flex flex-row items-start flex-nowrap">
          <section className="grow-0 h-screen shadow">
            <Image
              src="/assets/bg-auth.svg"
              alt="logo"
              width={200}
              height={200}
              className="w-full h-full bg-cover"
            />
          </section>
          <section className="grow mr-5 min-h-screen pt-8 overflow-y-auto">
            {children}
          </section>
        </section>
      </body>
    </html>
  );
}
