import { Metadata } from "next";
import AccountPages from "./components/AccountPages";

export const metadata: Metadata = {
  title: "Settings Account | SkyFly",
  description: "Generated by create next app",
};

export default function AccountPage() {
  return <AccountPages />;
}
